### ISSUE TITLE
v3.0.1 Still breaking the build with a new error

### ISSUE THREAD

**Issue by yoanmalie** [sindresorhus/vinyl-paths#9]
Hello,
I'm curently making a new Gulp setup. The last time I tried vinyl-paths I get the error mentioned here : https://github.com/sindresorhus/vinyl-paths/issues/7 . So now I see it's fixed I give it another try but it look like it's still broken for me.

`gulp styles:build`:
> TypeError: pathCallback is not a function
    at /Users/yoan/Projets/static-starter-plus/node_modules/vinyl-paths/index.js:11:12
    at DestroyableTransform._transform (/Users/yoan/Projets/static-starter-plus/node_modules/vinyl-paths/index.js:18:6)
    at DestroyableTransform.Transform._read (/Users/yoan/Projets/static-starter-plus/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/yoan/Projets/static-starter-plus/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/yoan/Projets/static-starter-plus/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/yoan/Projets/static-starter-plus/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/yoan/Projets/static-starter-plus/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/Users/yoan/Projets/static-starter-plus/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:466:23)

I created a repo here if you want to give a look on my config. https://github.com/yoanmalie/gulp-bug-vinyl

**Versions**
Node.js: 10.17.0
NPM: 6.12.0
Gulp: CLI 2.0.1, Local 4.0.2

**Comment by sindresorhus** [comment]
The error says it all. You're supposed to pass a callback **function**, but you're passing a promise.
